name: selector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  adaptive_theme: ^2.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  enum_to_string: ^2.0.1
  settings_ui: ^1.0.0
  material_floating_search_bar: ^0.3.4
  path_provider: ^2.0.2
  network_to_file_image: ^3.0.0
  flutter_barcode_scanner: ^2.0.0
  rxdart: ^0.27.1
  get_it: ^7.2.0
  tuple: ^2.0.0
  im_stepper: ^0.1.3
  progress_indicators: ^1.0.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^8.1.4+2
  string_similarity: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  flutter_launcher_icons: "^0.9.2"
  flutter_lints:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/connection.png
    - assets/platine.gif
    - assets/missing.png
    - assets/barcode_scanner.png
    - .env
