name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Set up environment
        run: flutter pub run environment_config:generate --discogsToken=${{ secrets.DICOGS_TOKEN }}
      - name: Test
        run: flutter test
      - name: Generate localization
        run: flutter pub run build_runner build | flutter pub get
      - name: Launcher icon
        run: flutter pub run flutter_launcher_icons:main
      - name: Build apk
        run: flutter build apk --split-per-abi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build\app\outputs\flutter-apk\app-armeabi-v7a-release.apk
